### PR TITLE
Add each block [Issue #3]

### PR DESCRIPTION
**Pull request by ryanong**
#3

### CODE REVIEW

**Comment by stefankroes** [comment]
Hey @ryanong !

Thx for helping out! You implementation is elegant and correct!

However, I think this method should be registered on Array instead of Object. Otherwise users will be able to call it on anything, including objects that don't support map which will raise a NameError.

Additionally, before I merge this, I think we should make sure Array also has a name and cast methods registered so it will play nice with error messages and things like `if`-statements when passed into Scribble. This can be done by adding array to the objects folder, similarly to Fixnum and such.

Thx again for showing interest and helping out!

Kind regards,

Stefan

**Comment by ryanong** [comment]
I'll make an Array method now. Do you think it would be possible to actually register this method on any Enumerable?

**Comment by stefankroes** [comment]
Yes, I think that would be a good idea!

**Comment by ryanong** [comment]
Hey @stefankroes, we ran into an issue with this code.
If any of the nodes inside the block are a Call, the `#evaluated_receiver` is cached on the first iteration and the set_variable is not re-evaluated. We thought about 3 options.
1. adding a `#reset` command that resets all the `#evaluated_receiver` methods on all the nested call nodes
2. adding a `#deep_clone` method and executing it before the first iteration
3. removing the caching of `#evaluated` receiver

Have any other ideas or preferences?

**Comment by stefankroes** [comment]
I see. Obviously another mistake on my part. 

I'd prefer to remove the caching instead of adding extra complexity in order to work around the faulty caching. You should also remove that caching in evaluated_args as it will cause similar problems.

We can take a look at performance later if necessary.

**Comment by ryanong** [comment]
I don't think I am going to be able to implement Array in the immediate future. Is there anything I could do to get this merged now without the Array type?

**Comment by stefankroes** [comment]
No problem

**Pull request merged**
